services:
  parking-database:
    image: postgres:14.17-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: parkingFlow

volumes:
  postgres-data:
