services:
  webapi:
    image: ${DOCKER_REGISTRY-}parkingflowwebapi
    build:
      context: .
      dockerfile: ParkingFlow.WebApi/Dockerfile
    depends_on:
       database:
          condition: service_healthy
          restart: true
  database:
    image: postgres:14.18-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parkingFlow
    ports: 
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

